volumes:
  postgres_data:
  event_store_data:
  minio_data:
  redpanda_data:
  kms_shared:
  clamav_data:
  airflow_postgres_data:
  oltp_data:
  debezium_offsets:

networks:
  platform_public:
    driver: bridge
  platform_internal:
    driver: bridge
    internal: true
