-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ingestion_run
(
    run_id uuid NOT NULL,
    source_type ingestion_source NOT NULL,
    status ingestion_status NOT NULL,
    triggered_by text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    PRIMARY KEY (run_id)
);

CREATE TABLE IF NOT EXISTS public.raw_artifact
(
    artifact_id uuid NOT NULL,
    run_id uuid NOT NULL,
    stage artifact_stage NOT NULL,
    format artifact_format NOT NULL,
    storage_path text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    PRIMARY KEY (artifact_id)
);

CREATE TABLE IF NOT EXISTS public.lineage_record
(
    id uuid NOT NULL,
    run_id uuid NOT NULL,
    input_artifact_id uuid NOT NULL,
    output_artifact_id uuid NOT NULL,
    transformation text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.raw_artifact
    ADD CONSTRAINT raw_artifact_run_id_fk FOREIGN KEY (run_id)
    REFERENCES public.ingestion_run (run_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lineage_record
    ADD CONSTRAINT lineage_record_run_id_fk FOREIGN KEY (run_id)
    REFERENCES public.ingestion_run (run_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lineage_record
    ADD CONSTRAINT lineage_record_input_artifact_id_fk FOREIGN KEY (input_artifact_id)
    REFERENCES public.raw_artifact (artifact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lineage_record
    ADD CONSTRAINT lineage_record_outut_artifact_id_fk FOREIGN KEY (output_artifact_id)
    REFERENCES public.raw_artifact (artifact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;