-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ingestion_run
(
    run_id uuid NOT NULL DEFAULT gen_random_uuid(),
    source_type ingestion_source NOT NULL,
    status ingestion_status NOT NULL,
    triggered_by text NOT NULL,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone,
    PRIMARY KEY (run_id)
);

CREATE TABLE IF NOT EXISTS public.artifact
(
    artifact_id uuid NOT NULL DEFAULT gen_random_uuid(),
    run_id uuid NOT NULL,
    stage artifact_stage NOT NULL,
    format artifact_format NOT NULL,
    storage_path text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (artifact_id)
);

CREATE TABLE IF NOT EXISTS public.lineage_record
(
    lineage_id uuid NOT NULL DEFAULT gen_random_uuid(),
    run_id uuid NOT NULL,
    input_artifact_id uuid NOT NULL,
    output_artifact_id uuid NOT NULL,
    transformation text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (lineage_id)
);

ALTER TABLE IF EXISTS public.artifact
    ADD CONSTRAINT artifact_run_id_fk FOREIGN KEY (run_id)
    REFERENCES public.ingestion_run (run_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS artifact_run_id_fki
    ON public.artifact(run_id);


ALTER TABLE IF EXISTS public.lineage_record
    ADD CONSTRAINT lineage_record_run_id_fk FOREIGN KEY (run_id)
    REFERENCES public.ingestion_run (run_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS lineage_record_run_id_fki
    ON public.lineage_record(run_id);


ALTER TABLE IF EXISTS public.lineage_record
    ADD CONSTRAINT lineage_record_input_artifact_id_fk FOREIGN KEY (input_artifact_id)
    REFERENCES public.artifact (artifact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS lineage_record_input_artifact_id_fki
    ON public.lineage_record(input_artifact_id);


ALTER TABLE IF EXISTS public.lineage_record
    ADD CONSTRAINT lineage_record_output_artifact_id_fk FOREIGN KEY (output_artifact_id)
    REFERENCES public.artifact (artifact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS lineage_record_output_artifact_id_fki
    ON public.lineage_record(output_artifact_id);

END;
